baseURL = 'https://ooh.mg/'
languageCode = 'pt-br'
title = 'OohMG!'

DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]

[params]
title = "OohMG"
description = "A maneira mais fácil de planejar, reservar e avaliar a publicidade out-of-home (OOH)."
mainSections = ["blog"]

[menu]

  [[menu.main]]
  name = "Nossos planos"
  identifier = "planos"
  weight = 10
  url = "/planos/"

  [[menu.main]]
  name = "Serviços adicionais"
  identifier = "servicos"
  weight = 10
  url = "/servicos"

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
